### ISSUE TITLE
Error in running the test.sh file 

### ISSUE THREAD

**Issue by kabbas570** [DIAGNijmegen/picai_nnunet_gc_algorithm#1]
Hello, can you please help for this error, Thanks 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK-0.9.1.post2-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 7724, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /usr/src/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:71:
sitk::ERROR: The file "/output/images/cspca-detection-map/cspca_detection_map.mha" does not exist.
Expected detection map was not found...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/output/cspca-case-level-likelihood.json'
Expected case-level prediction was not found...
picai_baseline_nnunet_processor-output-8302c9287b

**Comment by joeranbosma** [comment]
Hi,
This error is generated by the final part of the test.sh script and indicates that the detection algorithm did not produce an output. You should have more output logs that indicate what went wrong with the algorithm itself. What more do the logs indicate?
Best, Joeran

**Comment by kabbas570** [comment]
Thanks for the update; the issue is solved, as there was a mounting issue with the image's path at input volume.
